import os

EMAIL_PREFERENCE_SHEET_URL = os.getenv("EMAIL_PREFERENCE_SHEET_URL")

SMTP_HOST = os.environ["SMTP_HOST"]
SMTP_USERNAME = os.environ["SMTP_USERNAME"]
SMTP_PASSWORD = os.environ["SMTP_PASSWORD"]

WAFER_BASE_URL = os.getenv("WAFER_BASE_URL")
WAFER_USERNAME = os.getenv("WAFER_USERNAME")
WAFER_PASSWORD = os.getenv("WAFER_PASSWORD")

GOOGLE_SHEETS_CREDENTIALS_FILE = os.getenv("GOOGLE_SHEETS_CREDENTIALS_FILE")
