import os

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

EMAIL_PREFERENCE_SHEET_URL = os.getenv('EMAIL_PREFERENCE_SHEET_URL')

# SMTP_FROM_EMAIL = os.environ["SMTP_FROM_EMAIL"]

